# dev environment
name: React application deploy

on:
  push:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.18.0]
    steps:
      - name: Checkout the Files
        uses: actions/checkout@v2

      - name: Copy files to folder
        uses: appleboy/scp-action@master
        with:
          host: 194.233.75.156
          username: admin
          password: ${{ secrets.passwd }}
          source: "*"
          target: "~/frontend/"
          rm: true

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
      - run: yarn add jsvectormap/dist/maps/us-merc-en.js
      - run: npm install -g pm2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 194.233.75.156
          username: admin
          password: ${{ secrets.passwd }}
          port: 22
          script: |
            cd ~/frontend/

            # Build the React application
            npm run build

            # Start the application using pm2
            pm2 delete frontend || true
            pm2 start serve -n -s build -l 35000 --name "frontend"
            pm2 save
